FROM registry.access.redhat.com/ubi9/go-toolset:1.21 AS golang

USER 0

COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download
COPY . .
RUN CGO_ENABLED=1 GOFLAGS="" GO111MODULE=on go build -o /assisted-image-service main.go

FROM quay.io/centos/centos:stream9

ARG DATA_DIR=/data
RUN mkdir $DATA_DIR && chmod 775 $DATA_DIR
VOLUME $DATA_DIR
ENV DATA_DIR=$DATA_DIR

COPY --from=golang /assisted-image-service /assisted-image-service
CMD ["/assisted-image-service"]
