// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/assisted-image-service/pkg/imagestore (interfaces: ImageStore)
//
// Generated by this command:
//
//	mockgen -package=imagestore -destination=mock_imagestore.go . ImageStore
//

// Package imagestore is a generated GoMock package.
package imagestore

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockImageStore is a mock of ImageStore interface.
type MockImageStore struct {
	ctrl     *gomock.Controller
	recorder *MockImageStoreMockRecorder
	isgomock struct{}
}

// MockImageStoreMockRecorder is the mock recorder for MockImageStore.
type MockImageStoreMockRecorder struct {
	mock *MockImageStore
}

// NewMockImageStore creates a new mock instance.
func NewMockImageStore(ctrl *gomock.Controller) *MockImageStore {
	mock := &MockImageStore{ctrl: ctrl}
	mock.recorder = &MockImageStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageStore) EXPECT() *MockImageStoreMockRecorder {
	return m.recorder
}

// HaveVersion mocks base method.
func (m *MockImageStore) HaveVersion(version, arch string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HaveVersion", version, arch)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HaveVersion indicates an expected call of HaveVersion.
func (mr *MockImageStoreMockRecorder) HaveVersion(version, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HaveVersion", reflect.TypeOf((*MockImageStore)(nil).HaveVersion), version, arch)
}

// NmstatectlPathForParams mocks base method.
func (m *MockImageStore) NmstatectlPathForParams(openshiftVersion, arch string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NmstatectlPathForParams", openshiftVersion, arch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NmstatectlPathForParams indicates an expected call of NmstatectlPathForParams.
func (mr *MockImageStoreMockRecorder) NmstatectlPathForParams(openshiftVersion, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NmstatectlPathForParams", reflect.TypeOf((*MockImageStore)(nil).NmstatectlPathForParams), openshiftVersion, arch)
}

// PathForParams mocks base method.
func (m *MockImageStore) PathForParams(imageType, version, arch string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathForParams", imageType, version, arch)
	ret0, _ := ret[0].(string)
	return ret0
}

// PathForParams indicates an expected call of PathForParams.
func (mr *MockImageStoreMockRecorder) PathForParams(imageType, version, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathForParams", reflect.TypeOf((*MockImageStore)(nil).PathForParams), imageType, version, arch)
}

// Populate mocks base method.
func (m *MockImageStore) Populate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Populate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Populate indicates an expected call of Populate.
func (mr *MockImageStoreMockRecorder) Populate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Populate", reflect.TypeOf((*MockImageStore)(nil).Populate), ctx)
}
