apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/assisted-image-service?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "release-ocm-2.15"
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: assisted-installer-application-acm-ds-2-15
    appstudio.openshift.io/component: assisted-image-service-acm-ds-2-15
    pipelines.appstudio.openshift.io/type: build
  name: assisted-image-service-acm-ds-2-15-on-push
  namespace: assisted-installer-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/assisted-installer-tenant/assisted-installer-application-acm-ds-2-15/assisted-image-service-acm-ds-2-15:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/arm64
    - linux/ppc64le
    - linux/s390x
  - name: dockerfile
    value: Dockerfile.image-service-mce
  - name: path-context
    value: .
  - name: build-args
    value:
    - release={{target_branch}}
    - version={{revision}}
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: '[{"type": "gomod", "path": "."}, {"type": "rpm", "path": "./rpm-prefetching/"}]'
  - name: build-source-image
    value: "true"
  - name: sast-snyk-check-args
    value: "--project-name=assisted-image-service --report --org=3e6fd93b-b325-49dd-8a33-432a0160ab66"
  - name: send-slack-webhook-notification-on-fail
    value: "true"
  - name: slack-webhook-notification-secret
    value: slack-notif-webhook
  - name: slack-webhook-notification-secret-key
    value: token
  - name: slack-webhook-notification-message
    value: "[ACM] [2.15] [assisted-image-service] [{{revision}}] [<https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/assisted-installer-tenant/applications/assisted-installer-application-acm-ds-2-15/pipelineruns/$(context.pipelineRun.name)|pipeline>] Konflux build failed"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/openshift-assisted/assisted-installer-konflux-pipelines.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: "pipelines/standard-pipeline.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-assisted-image-service-acm-ds-2-15
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
