apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/assisted-image-service?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: assisted-image-service-saas-main
    appstudio.openshift.io/component: assisted-image-service-saas-main
    pipelines.appstudio.openshift.io/type: build
  name: assisted-image-service-saas-main-on-pull-request
  namespace: assisted-installer-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/assisted-installer-tenant/assisted-image-service-saas-main/assisted-image-service-saas-main:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Dockerfile.image-service
  - name: path-context
    value: .
  - name: build-args
    value:
    - release={{target_branch}}
    - version={{revision}}
  - name: build-source-image
    value: "true"
  - name: sast-snyk-check-args
    value: "--project-name=assisted-image-service --report --org=3e6fd93b-b325-49dd-8a33-432a0160ab66"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/openshift-assisted/assisted-installer-konflux-pipelines.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: "pipelines/standard-pipeline.yaml"
  taskRunTemplate:
    serviceAccountName: build-pipeline-assisted-image-service-saas-main
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
