name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Test
      run: make test
      
    - name: Build Image
      uses: redhat-actions/buildah-build@v2
      with:
        image: test-assisted-image-service
        dockerfiles: |
          ./Dockerfile.image-service
